version: '3.9'

services:
  tautulli:
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuching
    volumes:
      - /data/tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped